# Generated by Django 3.0.5 on 2023-05-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=50, null=True)),
                ('camp_venue', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('organizer', models.CharField(max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('starttime', models.CharField(max_length=50, null=True)),
                ('endtime', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
