# Generated by Django 3.2 on 2024-04-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('blood', '0005_donationcamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_by_hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
